version: '3.7'

services:
  postgres:
    image: postgres:15
    ports:
      - "54321:5432"
    volumes:
      - ~/apps/logiaudit/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=logiaudit
      - POSTGRES_PASSWORD=logiaudit
      - POSTGRES_DB=logiaudit
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.10.0/24
